### PR TITLE
ES6-ified more

### PR DESCRIPTION
**Pull request by vihanb**
that exports.default was bothering me >_>

### CODE REVIEW

**Comment by ConorOBrien-Foxx** [comment]
I don't think node works like this, does it?

**Comment by vihanb** [comment]
it doesn't support `export` yet but babel does.

**Comment by vihanb** [comment]
`"use strict";` is implicit with ES6

**Comment by ConorOBrien-Foxx** [comment]
I see the latter. However, this was meant to work with vanilla node. Feel free to submit a babel version, however.

**Comment by vihanb** [comment]
okay

**Comment by ConorOBrien-Foxx** [comment]
That picture... is terrifying.

**Comment by vihanb** [comment]
:|

**Pull request closed without merging**
